sudo: false
language: node_js
node_js:
  - '6'
before_script:
  - 'npm install -g grunt-cli bower'
  - 'bower install'
script:
  - 'grunt jshint'
  - 'grunt jscs'
  - 'grunt test'
after_success:
  - bash <(curl -s https://codecov.io/bash)
